/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicio;

/**
 *
 * @author lucia
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnproveedores = new javax.swing.JButton();
        btnclientes = new javax.swing.JButton();
        btnpersonal = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Rasa SemiBold", 1, 48)); // NOI18N
        jLabel5.setText("¡Bienvenid@!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 350, -1));

        jLabel3.setFont(new java.awt.Font("Nimbus Mono L", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LIBRERÍA");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 60));

        jLabel4.setFont(new java.awt.Font("Nimbus Mono L", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOHMÉ");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/679bfe35aec4818f76446a9bc352767e.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 240, 620));

        btnsalir.setBackground(new java.awt.Color(153, 255, 153));
        btnsalir.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalirMouseClicked(evt);
            }
        });
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        background.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rasa SemiBold", 1, 24)); // NOI18N
        jLabel6.setText("¿A qué tabla desea ingresar?");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 310, 50));

        jLabel7.setFont(new java.awt.Font("Manjari Thin", 3, 36)); // NOI18N
        jLabel7.setText("-------------------------");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 310, 20));

        btnproveedores.setBackground(new java.awt.Color(153, 255, 153));
        btnproveedores.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnproveedores.setText("Proveedores");
        btnproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproveedoresMouseClicked(evt);
            }
        });
        btnproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedoresActionPerformed(evt);
            }
        });
        background.add(btnproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 150, 30));

        btnclientes.setBackground(new java.awt.Color(153, 255, 153));
        btnclientes.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnclientes.setText("Clientes");
        btnclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclientesMouseClicked(evt);
            }
        });
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        background.add(btnclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 110, 30));

        btnpersonal.setBackground(new java.awt.Color(153, 255, 153));
        btnpersonal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnpersonal.setText("Personal");
        btnpersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpersonalMouseClicked(evt);
            }
        });
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });
        background.add(btnpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 110, 30));

        btnventas.setBackground(new java.awt.Color(153, 255, 153));
        btnventas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnventas.setText("Ventas");
        btnventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnventasMouseClicked(evt);
            }
        });
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        background.add(btnventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 30));

        btnproductos.setBackground(new java.awt.Color(153, 255, 153));
        btnproductos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnproductos.setText("Productos");
        btnproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproductosMouseClicked(evt);
            }
        });
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        background.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/cf684671e628d546a9a7aecf1974504f.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 630, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproveedoresActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnventasActionPerformed

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproductosActionPerformed

    private void btnsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnsalirMouseClicked

    private void btnclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclientesMouseClicked
        Clientes clientes= new Clientes ();
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnclientesMouseClicked

    private void btnventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventasMouseClicked
        Ventas ventas= new Ventas ();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnventasMouseClicked

    private void btnproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproductosMouseClicked
        Productos productos= new Productos ();
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnproductosMouseClicked

    private void btnproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproveedoresMouseClicked
        Proveedores proveedores= new Proveedores ();
        proveedores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnproveedoresMouseClicked

    private void btnpersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpersonalMouseClicked
        Personal personal= new Personal ();
        personal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpersonalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btnpersonal;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnproveedores;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
